//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBookApp.Models
{
    using CsvHelper.Configuration.Attributes;
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneBook
    {
        [Index(0)]
        public string Name { get; set; }
        [Index(1)]
        public string Gender { get; set; }
        [Index(2)]
        public string Date_of_birth { get; set; }
        [Index(3)]
        public string Email { get; set; }
        [Index(4)]
        public string Phone { get; set; }
        [Index(5)]
        public string Photo { get; set; }
        [Index(6)]
        public string Address { get; set; }
    }
}
